#!/usr/bin/env bash
# A Bash script that displays "To infinity and beyond" indefintely with
#+ a sleep 2 in between each iteration.
# Displays "I am Invincible!!!" in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM
done 
