#!/usr/bin/env bash
# Script that displays "Best School" 10 times using a while loop.
# on the 9th iteration, displays "Hi" then the rest "Best School"

i=0

while [ $i -lt 10 ]
do
  if [ $i -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( i++ ))
done
